# Test the CPI Data

In [1]:
# If not already installed, do: pip install pandas fastparquet
import pandas as pd

URL_DATA = 'https://storage.dosm.gov.my/cpi/cpi_2d_inflation.parquet'

df = pd.read_parquet(URL_DATA)
if 'date' in df.columns: df['date'] = pd.to_datetime(df['date'])

print(df)

           date division  inflation_yoy  inflation_mom
0    2000-02-01  overall            NaN            0.1
1    2000-03-01  overall            NaN           -0.1
2    2000-04-01  overall            NaN            0.0
3    2000-05-01  overall            NaN            0.1
4    2000-06-01  overall            NaN            0.0
...         ...      ...            ...            ...
4377 2025-10-01       13            6.0            1.4
4378 2025-11-01       13            5.6            0.1
4379 2025-12-01       13            5.7            0.1
4380 2026-01-01       13            6.6            1.0
4381 2026-02-01       13            6.9            1.0

[4382 rows x 4 columns]

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4382 entries, 0 to 4381
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           4382 non-null   datetime64[ns]
 1   division       4382 non-null   object
 2   inflation_yoy  3928 non-null   float64
 3   inflation_mom  4082 non-null   float64
dtypes: datetime64[ns](1), float64(2), object(1)
memory usage: 137.1+ KB

In [3]:
df_cpi = df[df['division']=='overall']

In [4]:
df_cpi

          date division  inflation_yoy  inflation_mom
0   2000-02-01  overall            NaN            0.1
1   2000-03-01  overall            NaN           -0.1
2   2000-04-01  overall            NaN            0.0
3   2000-05-01  overall            NaN            0.1
4   2000-06-01  overall            NaN            0.0
..         ...      ...            ...            ...
308 2025-10-01  overall            1.3           -0.1
309 2025-11-01  overall            1.4            0.0
310 2025-12-01  overall            1.6            0.3
311 2026-01-01  overall            1.6            0.1
312 2026-02-01  overall            1.4            0.2

[313 rows x 4 columns]

In [6]:
# If not already installed, do: pip install pandas fastparquet
import pandas as pd

URL_DATA = 'https://storage.data.gov.my/commodities/fuelprice.parquet'

df_fuel = pd.read_parquet(URL_DATA)
if 'date' in df_fuel.columns: df_fuel['date'] = pd.to_datetime(df_fuel['date'])

print(df_fuel)

       series_type       date  ron95  ron97  diesel  diesel_eastmsia  \
0            level 2017-03-30   2.13   2.41    2.11             2.11
1            level 2017-04-06   2.16   2.43    2.08             2.08
2            level 2017-04-13   2.24   2.52    2.16             2.16
3            level 2017-04-20   2.27   2.54    2.21             2.21
4            level 2017-04-27   2.21   2.49    2.14             2.14
..             ...        ...    ...    ...     ...              ...
908  change_weekly 2026-03-19   0.00   0.70    0.80             0.00
909  change_weekly 2026-03-26   0.60   0.60    0.80             0.00
910  change_weekly 2026-04-02   0.00  -0.20    0.50             0.00
911  change_weekly 2026-04-09   0.40   0.40    0.70             0.00
912  change_weekly 2026-04-16  -0.25  -0.25   -0.75             0.00

     ron95_budi95  ron95_skps
0             NaN         NaN
1             NaN         NaN
2             NaN         NaN
3             NaN         NaN
4             NaN         NaN
..            ...         ...
908           0.0         0.0
909           0.0         0.0
910           0.0         0.0
911           0.0         0.0
912           0.0         0.0

[913 rows x 8 columns]

In [7]:
df_fuel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 913 entries, 0 to 912
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   series_type      913 non-null    object
 1   date             913 non-null    datetime64[ns]
 2   ron95            913 non-null    float64
 3   ron97            913 non-null    float64
 4   diesel           913 non-null    float64
 5   diesel_eastmsia  913 non-null    float64
 6   ron95_budi95     57 non-null     float64
 7   ron95_skps       57 non-null     float64
dtypes: datetime64[ns](1), float64(6), object(1)
memory usage: 57.2+ KB

In [9]:
df_fuel['series_type'].unique()

array(['level', 'change_weekly'], dtype=object)

In [10]:
if 'series_type' in df_fuel.columns:
    df_fuel = df_fuel[df_fuel['series_type'] == 'level']

In [12]:
df_fuel.head()

,series_type,date,ron95,ron97,diesel,diesel_eastmsia,ron95_budi95,ron95_skps
0,level,2017-03-30,2.13,2.41,2.11,2.11,NaN,NaN
1,level,2017-04-06,2.16,2.43,2.08,2.08,NaN,NaN
2,level,2017-04-13,2.24,2.52,2.16,2.16,NaN,NaN
3,level,2017-04-20,2.27,2.54,2.21,2.21,NaN,NaN
4,level,2017-04-27,2.21,2.49,2.14,2.14,NaN,NaN